<?php

require FSQL_FRONTENDS_PATH.'/standard/fSQLStandardParser.php';

class fSQLStandardFrontend
{
	function &createFunctions(&$env)
	{
		fsql_load_class('fSQLStandardFunctions', FSQL_FRONTENDS_PATH.'/standard');
		$funcs =& new fSQLStandardFunctions($env);
		return $funcs;
	}
	
	function &createParser(&$env)
	{
		$parser =& new fSQLStandardParser($env);
		return $parser;
	}
	
	function getTypes()
	{
		return array(
			'CHAR' => FSQL_TYPE_STRING,
			'CHAR LARGE OBJECT' => FSQL_TYPE_STRING,
			'CHAR VARYING' => FSQL_TYPE_STRING,
			'CHARACTER' => FSQL_TYPE_STRING,
			'CHARACTER LARGE OBJECT' => FSQL_TYPE_STRING,
			'CHARACTER VARYING' => FSQL_TYPE_STRING,
			'CLOB' => FSQL_TYPE_STRING,
			'VARCHAR' => FSQL_TYPE_STRING,
			
			'NATIONAL CHAR' => FSQL_TYPE_STRING,
			'NATIONAL CHAR VARYING' => FSQL_TYPE_STRING,
			'NATIONAL CHARACTER' => FSQL_TYPE_STRING,
			'NATIONAL CHARACTER LARGE OBJECT' => FSQL_TYPE_STRING,
			'NATIONAL CHARACTER VARYING' => FSQL_TYPE_STRING,
			'NCHAR' => FSQL_TYPE_STRING,
			'NCHAR LARGE OBJECT' => FSQL_TYPE_STRING,
			'NCHAR VARYING' => FSQL_TYPE_STRING,
			'NCLOB' => FSQL_TYPE_STRING,
			'NVARCHAR' => FSQL_TYPE_STRING,
			
			'BINARY' => FSQL_TYPE_STRING,
			'BINARY LARGE OBJECT' => FSQL_TYPE_STRING,
			'BINARY VARYING' => FSQL_TYPE_STRING,
			'BLOB' => FSQL_TYPE_STRING,
			'VARBINARY' => FSQL_TYPE_STRING,
			
			'TEXT' => FSQL_TYPE_STRING,
			
			'BIT' => FSQL_TYPE_INTEGER,
			'SMALLINT' => FSQL_TYPE_INTEGER,
			'INT' => FSQL_TYPE_INTEGER,
			'INTEGER' => FSQL_TYPE_INTEGER,
			'BIGINT' => FSQL_TYPE_INTEGER,
			
			'FLOAT' => FSQL_TYPE_FLOAT,
			'REAL' => FSQL_TYPE_FLOAT,
			'DOUBLE' => FSQL_TYPE_FLOAT,
			'DOUBLE PRECISION' => FSQL_TYPE_FLOAT,
			'NUMERIC' => FSQL_TYPE_FLOAT,
			'DEC' => FSQL_TYPE_FLOAT,
			'DECIMAL' => FSQL_TYPE_FLOAT,
			
			'ENUM' => FSQL_TYPE_ENUM,
			
			'DATE' => FSQL_TYPE_DATE,
			'TIME'  => FSQL_TYPE_TIME,
			'TIME WITH TIME ZONE'  => FSQL_TYPE_TIME_WITH_TZ,
			'TIME WITHOUT TIME ZONE'  => FSQL_TYPE_TIME,
			'TIMESTAMP' => FSQL_TYPE_TIMESTAMP,
			'TIMESTAMP WITH TIME ZONE'  => FSQL_TYPE_TIMESTAMP_WITH_TZ,
			'TIMESTAMP WITHOUT TIME ZONE' => FSQL_TYPE_TIMESTAMP,
		);
	}
}

?>